MemberManagement/Controllers/BranchController.cs
using AutoMapper;
using MemberManagement.Application.DTO.BranchDTO;
using MemberManagement.Application.Interface;
using MemberManagement.Application.Services;
using MemberManagement.Domain.Entities;
using MemberManagement.Web.ViewModels.BranchVM;
using MemberManagement.Web.ViewModels.MemberVM;
using Microsoft.AspNetCore.Mvc;

namespace MemberManagement.Web.Controllers
{
    public class BranchController : Controller
    {
        private readonly IBranchService _branchService;
        private readonly IMapper _mapper;
        public BranchController(IBranchService branchService, IMapper mapper)
        {
            ArgumentNullException.ThrowIfNull(branchService);
            ArgumentNullException.ThrowIfNull(mapper);
            _branchService = branchService;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var branchesDTO = (IEnumerable<BranchIndexDTO>)
                await _branchService.GetAll();
            List<BranchIndexViewModel> branchResultViewModel =
                new List<BranchIndexViewModel>();

            //auto mapping of a DTO to ViewModel
            foreach (var branchDTO in branchesDTO)
            {
                var branchViewModel = _mapper.Map<BranchIndexViewModel>(branchDTO);
                branchResultViewModel.Add(branchViewModel);
            }
            return View(branchResultViewModel);
        }

        //Open the create member page
        public IActionResult Create()
        {
            var branchCreateViewModel = new BranchCreateViewModel();
            return View(branchCreateViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BranchCreateViewModel branchViewModel)
        {
            var branch = _mapper.Map<Branch>(branchViewModel);
            if (ModelState.IsValid)
            {
                var checkBranch = _branchService.AddBranch(branch);
                if (checkBranch == false)
                {
                    ModelState.AddModelError("", "The branch you are trying to add is already in the list.");

                    var branchCreateViewModel = _mapper.Map<BranchCreateViewModel>(branch);

                    //Reopen the create page with the values entered
                    return View(branchCreateViewModel);
                }
                //else, success in creating the member will redirect to all members' page
                return RedirectToAction(nameof(Index));
            }
            return View(branch);
        }

        //View a specific member
        public async Task<IActionResult> Detail(int id)
        {
             var branchDTO = await _branchService.DetailBranch(id);
             //check if Member exists
             if (branchDTO.BranchName == null)
             {
                 ModelState.AddModelError("", "The Branch you're trying to access does not exist.");
                 return View();
             }
             var branchViewModel = _mapper.Map<BranchDetailViewModel>(branchDTO);
             return View(branchViewModel);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var branchDTO = await _branchService.EditBranch(id);
            if (branchDTO.BranchName == null)
            {
                ModelState.AddModelError("", "The Branch you're trying to edit does not exist.");
                return View();
            }

            var branchViewModel = _mapper.Map<BranchEditViewModel>(branchDTO);

            return View(branchViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BranchEditViewModel branchViewModel)
        {
            if (id != branchViewModel.BranchID)
            {
                return NotFound();
            }
            var branch = _mapper.Map<Branch>(branchViewModel);
            //Check for input validation
            if (ModelState.IsValid)
            {
                await _branchService.SaveEditBranch(id, branch);
                return RedirectToAction("Index");
            }
            return View(branch);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var branchDTO = await _branchService.DeleteBranch(id);

            //Return an empty Delete page
            //since member does not exists
            if (branchDTO.BranchName == null)
            {
                ModelState.AddModelError("", "The Branch you're trying to delete does not exist.");
                return View();
            }

            //Else, will continue to open the delete page with the member's details
            var branchViewModel = _mapper.Map<BranchDeleteViewModel>(branchDTO);

            return View(branchViewModel);
        }

        //Process to replace IsActive value to false
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _branchService.DeleteConfirmed(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

MemberManagement/Controllers/MemberController.cs
using AutoMapper;
using MemberManagement.Application.DTO.MemberDTO;
using MemberManagement.Application.Interface;
using MemberManagement.Application.Services;
using MemberManagement.Web.ViewModels.MemberVM;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Member = MemberManagement.Domain.Entities.Member;

namespace MemberManagement.Web.Controllers
{
    public class MemberController : Controller
    {
        private readonly IMemberService _memberService;
        private readonly IMapper _mapper;
        public MemberController(IMemberService memberService, IMapper mapper)
        {
            ArgumentNullException.ThrowIfNull(memberService);
            ArgumentNullException.ThrowIfNull(mapper);
            _memberService = memberService;
            _mapper = mapper;
        }

        //View all members
        public async Task<IActionResult> Index()
        {
            var membersDTO = (IEnumerable<MemberIndexDTO>)
                await _memberService.GetAll();
            
            List<MemberIndexViewModel> memberResultViewModel = 
                new List<MemberIndexViewModel>();

            //auto mapping of a DTO to ViewModel
            foreach (var memberDTO in membersDTO)
            {
                var memberViewModel = _mapper.Map<MemberIndexViewModel>(memberDTO);
                memberResultViewModel.Add(memberViewModel);
            }
            return View(memberResultViewModel);
        }

        //View all Active members
        public async Task<IActionResult> IndexActive()
        {
            var membersDTO = (IEnumerable<MemberActiveInactiveDTO>)
                await _memberService.GetAllActive();
            List<MemberActiveInactiveViewModel> memberResultViewModel = 
                new List<MemberActiveInactiveViewModel>();

            foreach (var memberDTO in membersDTO)
            {
                var memberViewModel = _mapper.Map<MemberActiveInactiveViewModel>(memberDTO);
                memberResultViewModel.Add(memberViewModel);
            }
            return View(memberResultViewModel);
        }

        //View all Inactive Members
        public async Task<IActionResult> IndexInactive()
        {
            var membersDTO = (IEnumerable<MemberActiveInactiveDTO>)
                await _memberService.GetAllInactive();
            List<MemberActiveInactiveViewModel> memberResultViewModel = 
                new List<MemberActiveInactiveViewModel>();
            foreach (var memberDTO in membersDTO)
            {
                var memberViewModel = _mapper.Map<MemberActiveInactiveViewModel>(memberDTO);
                memberResultViewModel.Add(memberViewModel);
            }
            return View(memberResultViewModel);
        }

        //View a specific member
        public async Task<IActionResult> Detail(int id)
        {
            var memberDTO = await _memberService.DetailMember(id);
            //check if Member exists
            if(memberDTO.LastName == null)
            {
                ModelState.AddModelError("", "The Member you're trying to access does not exist.");
                return View();
            }
            var memberViewModel = _mapper.Map<MemberDetailDeleteViewModel>(memberDTO);
            memberViewModel.IsActive = memberDTO.IsActive ? "YES" : "NO";
            return View(memberViewModel);
        }


        //Open the create member page
        public async Task<IActionResult> Create()
        {
            var memberCreateViewModel = new MemberCreateViewModel();
            ViewBag.BranchesList = new SelectList(await _memberService.GetBranches(),
                "BranchID", "BranchName");
            ViewBag.MembershipsList = new SelectList(await _memberService.GetMemberships(),
                "MembershipID", "MembershipType");
            return View(memberCreateViewModel);
        }

        //Processing of creating a member
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MemberCreateViewModel member)
        {
            var memberVMToMember = _mapper.Map<Member>(member);
            //Check if all input are valid
            if (ModelState.IsValid)
            {
                var checkMember = _memberService.AddMember(memberVMToMember);
                //If the member to be added is already in the list
                //will create an error and will pass the current values
                //in the form given by the user
                if (checkMember == false) {
                    ModelState.AddModelError("", "The member you are trying to add is already in the list.");
                    
                    var memberCreateViewModel = _mapper.Map<MemberCreateViewModel>(member);
                    
                    //Reopen the create page with the values entered
                    return View(memberCreateViewModel);
                }
                    //else, success in creating the member will redirect to all members' page
                    return RedirectToAction(nameof(Index));
            }
            ViewBag.BranchesList = new SelectList(await _memberService.GetBranches(),
                "BranchID", "BranchName");
            ViewBag.MembershipsList = new SelectList(await _memberService.GetMemberships(),
                "MembershipID", "MembershipType");
            return View(member);
        }

        //Open the Edit page of a member
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var memberDTO = await _memberService.EditMember(id);
            //Check if a member exists
            //If not, will create an error and open an empty Edit page
            if (memberDTO.LastName == null)
            {
                ModelState.AddModelError("", "The Member you're trying to edit does not exist.");
                return View();
            }

            //Else will continue to open the Edit page with the member's details
            var memberViewModel = _mapper.Map<MemberEditViewModel>(memberDTO);
            ViewBag.BranchesList = new SelectList(await _memberService.GetBranches(), 
                "BranchID", "BranchName", memberViewModel.MemberID);
            ViewBag.MembershipsList = new SelectList(await _memberService.GetMemberships(),
                "MembershipID", "MembershipType");

            //Else return to the page of Edit with the member's details
            return View(memberViewModel);
        }

        //Process on saving the edited member
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, MemberEditViewModel memberEditViewModel)
        {
            if (id != memberEditViewModel.MemberID)
            {
                return NotFound();
            }
            //Check for input validation
            var member = _mapper.Map<Member>(memberEditViewModel);
            if (ModelState.IsValid)
            {
                await _memberService.SaveEditMember(id, member);
                return RedirectToAction("Index");
            }
            ViewBag.BranchesList = new SelectList(await _memberService.GetBranches(),
                "BranchID", "BranchName", memberEditViewModel.MemberID);
            ViewBag.MembershipsList = new SelectList(await _memberService.GetMemberships(),
                "MembershipID", "MembershipType");
            return View(memberEditViewModel);
        }

        //Open the delete page of a member
        public async Task<IActionResult> Delete(int id)
        {
            var memberDTO = await _memberService.DeleteMember(id);

            //Return an empty Delete page
            //since member does not exists
            if (memberDTO.LastName == null)
            {
                ModelState.AddModelError("", "The Member you're trying to delete does not exist.");
                return View();
            }

            //Else, will continue to open the delete page with the member's details
            var memberViewModel = _mapper.Map<MemberDetailDeleteViewModel>(memberDTO);
            memberViewModel.IsActive = memberDTO.IsActive ? "YES" : "NO";

            return View(memberViewModel);
        }

        //Process to replace IsActive value to false
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _memberService.DeleteConfirmed(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

MemberManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Member Management</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MemberManagement.styles.css" asp-append-version="true" />
    <!-- Bootstrap Datatables css and jquery -->
    <link href="~/datatables/css/datatables.bootstrap4.css" rel="stylesheet" />
    <link href="~/datatables/css/datatables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/datatables/css/jquery.datatables.css" rel="stylesheet" />
    <link href="~/datatables/css/jquery.datatables.min.css" rel="stylesheet" />
    <!-- Bootstrap icons -->
    <link href="~/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Member Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Index">Member</a>
                        </li>
                        
                        <a class="nav-link text-dark" asp-area="" asp-controller="Branch" asp-action="Index">Branch</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Membership" asp-action="Index">Membership</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - MemberManagement
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/datatables/js/jquery.datatables.js"></script>
    <script src="~/datatables/js/jquery.datatables.min.js"></script>
    <script>
        $(document).ready(function(){
            $('#membersTable').DataTable();
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>